
name: deploy-api-docs
on:
  push:
    branches: [ master ]

jobs:
  deploy-api-docs:
    name: api.vapor.codes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set tag environment variable
        run: echo ::set-env name=TAG_VERSION::${GITHUB_REF#refs/*/}
      - name: generate api documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: "Sources"
          module-name: MyLibrary
          output: "Documentation"
      - name: copy generated documentation via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "Documentation/*"
          target: "docs/${{ env.TAG_VERSION }}"
